---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - iot.iambarton.com
  resources:
  - sensorgateways
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - iot.iambarton.com
  resources:
  - sensorgateways/finalizers
  verbs:
  - update
- apiGroups:
  - iot.iambarton.com
  resources:
  - sensorgateways/status
  verbs:
  - get
  - patch
  - update
