# This rule is not used by the project sensor-gateway-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over iot.iambarton.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: sensor-gateway-operator
    app.kubernetes.io/managed-by: kustomize
  name: sensorgateway-admin-role
rules:
- apiGroups:
  - iot.iambarton.com
  resources:
  - sensorgateways
  verbs:
  - '*'
- apiGroups:
  - iot.iambarton.com
  resources:
  - sensorgateways/status
  verbs:
  - get
