# This rule is not used by the project sensor-gateway-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the iot.iambarton.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: sensor-gateway-operator
    app.kubernetes.io/managed-by: kustomize
  name: sensorgateway-editor-role
rules:
- apiGroups:
  - iot.iambarton.com
  resources:
  - sensorgateways
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - iot.iambarton.com
  resources:
  - sensorgateways/status
  verbs:
  - get
