name: Build and Push Operator Image

on:
  push:
    # This workflow runs when you push a tag that starts with 'v' (e.g., v0.0.1, v1.2.3)
    tags:
      - 'v*.*.*'

jobs:
  build_and_push_operator:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository's code so the workflow can access it,
      # including the Makefile.
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx, which is required by the 'make docker-buildx' command.
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub using the secrets stored in your repository settings.
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 4: Run the 'make' command to build and push the operator image.
      # The `env` block sets the IMG environment variable for this specific step.
      # It dynamically creates the image tag using your Docker Hub username and the Git tag that triggered the workflow.
      - name: Build and push with make
        run: make docker-buildx
        env:
          IMG: ${{ secrets.DOCKERHUB_USERNAME }}/sensor-gateway-operator:${{ github.ref_name }}

